#williammarques
#https://github.com/swaskophf

#bibliotecas necessarias, caso nao tenha instalada em sua maquina basta executar os comandos (pip instal....)
from selenium import webdriver  #pip install selenium
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.by import By
from webdriver_manager.chrome import ChromeDriverManager #pip install webdriver_manager
import time

#Abre o Chrome
driver = webdriver.Chrome(ChromeDriverManager().install())
driver.get('https://web.whatsapp.com/') #abre o site Whatsapp Web
time.sleep(10) #da um sleep de 15 segundos, tempo para scannear o QRCODE

#Contatos/Grupos - Informar o nome(s) de Grupos ou Contatos que serao enviadas as mensagens
contatos = ['Cleber Specht',
'Gladimir Henrique Fae',
'Guilherme Damiani Janczura',
'Guilherme De Lima Bastos',
'Guilherme Mello Alves De Oliveira',
'Guilherme Oliveira Batista',
'Guilherme Pedro Konzen Ritter',
'Gustavo Alfonso Rocha',
'Gustavo Braz Carneiro',
'Gustavo Rocha Loures Christoval',
'Gustavo Rosendo Sanches De Freitas',
'Harold Saloah Hansen',
'Helcius Lorival Francisco',
'Helio Jose Cardoso',
'Henrique Ferreira De Freitas Miranda',
'Hercules Geraldo De Oliveira',
'Homar Mohamed El Ghandour',
'Homero Lopes De Almeida Aita',
'Igor Dos Santos Alonso',
'Igor Kovalscki Oswaldt',
'Ildo Volmir Drum',
'Indiara Noronha De Freitas Beckel',
'Ingrid Buschermoehle Juskow',
'Isabel Abreu Wagner',
'Isac Joao Benvenutti',
'Isolda Bertao',
'Isolda Kraemer Pantoja',
'JESSICA KAROLINE DOURADO BARCELOS',
'Jackson Dias Caldas',
'Jackson Luis Konell',
'Jacyr Silva Da Fonseca Junior',
'Jailton Do Carmo Constante',
'Jaime Carlos Selau',
'Jaine Alves De Camargo Vieira',
'Jair Jose De Souza',
'Jandira Custodia Da Rosa',
'Jeferson Oliveira Silva',
'Jefferson Bueno',
'Jhionatan Cardodo Rodrigues',
'Jhonatan Rista Cristo',
'Jian Carlo Dias Ienshaki',
'Joao Arrata Filho',
'Joao Batista Justo',
'Joao Bruno Da Silva',
'Joao Carlos Adams',
'Joao Carlos Correia De Lima',
'Joao Carlos De Oliveira Pimentel',
'Joao Roberto Da Silva Escarcel',
'Joaquim De Oliveira',
'Jocasta Telles Bassani',
'Jocelaine Vedoin',
'Jonathan De Abreu Barbosa',
'Jonnes De Moura',
'Jorge Aquino Aloar Dos Santos Fraga',
'Jorge Augusto Barcelos De Oliveira',
'Jorge Luiz Castilho De Souza',
'Jose Alberto Duarte Tessmer',
'Jose Claudio Matos',
'Jose Da Conceicao',
'Jose Donizete Dos Santos',
'Jose Luiz Escobar Madeira',
'Jose Pedro Ducati Marcon',
'Jose Walker Mostajo Cavero',
'Jose Xavier Silva',
'Jossemar Bressa Dalcin',
'Jovino Fonseca Da Encarnacao Filho',
'Juarez Joao Londero',
'Juarez Pereira Da Silva',
'Juliana De Franca Taborda',
'Juliana Pereira',
'Julio Cesar Zanatta',
'Juscelino de Almeida Junior',
'Jussaine Da Silveira Scopel',
'Karine Stefanie Camilo De Lima',
'Karla Cristina Mussalem Drago Schutte',
'Kelcey De Jesus Moreira',
'Laercio De Souza',
'Laureci De Fatima Alves Gomes',
'Leandro Candido Dos Reis',
'Leda Berenice Soares Otero',
'Leia Aparecida De Souza',
'Leomar Dos Anjos Rodrigues',
'Leonidas Da Silva Fritz',
'Leonir Paz Adiers',
'Liamar Wawrzyniak',
'Lindalva Lima De Oliveira',
'Loirema Gomes Dos Santos',
'#N/D',
'Luana Paz Heydt',
'#N/D',
'Luciano Da Costa',
'Luciano Gomes Dos Santos',
'Luciano Henrique De Oliveira',
'Luciano Oliveira De Oliveira',
'Luciano Silva Lobo',
'Lucimar Santo Das Chagas',
'Luis Carlos Das Neves Borges',
'Luis Edgar Padilha Ferreira',
'Luiz Alberto Dutra',
'Luiz Amauri Pereira',
'Luiz Carlos Santos De Oliveira',
'Luiz Cláudio Rosa Burgo',
'Luiz Fernando Ávila Freitas',
'Luiz Henrique Kielwagen Guimaraes',
'Luiz Minoru Ottani',
'Luiz Roberto Bonini',
'Luiz Waldemar De Barcelos Dexheimer',
'Maciel Itamar Da Nunciacao',
'Makley Goncalves',
'Mara Cristina Da Silva Fischer',
'Marcela De Oliveira Appel Dos Santos',
'Marcelo Aparecido Tosatti',
'Marcelo Gammardella',
'Marcelo Gasperi',
'Marcelo Silva Souza',
'Marcelo Soares Lopes',
'Marcelo Torronteguy Valle',
'Marcelo Wichmann',
'Marcia Adriana de Carli',
'Marcia Fernanda Lima Ramazini',
'Marcia Richter De Miranda',
'Marcia Teresinha Kihs Matiello',
'Marcio Cardoso de Freitas',
'Marcio Jose Nogueira Dos Santos',
'Marcio Machado Dos Santos',
'Marcio Roberto Felice',
'Marcio Rogerio Da Silva',
'Marco Antonio Andreotti',
'Marco Ondino Moraes Da Rosa',
'Marcos Andre Guimaraes Rodrigues',
'Marcos Antonio Vieira',
'Marcos Rodrigues',
'Marcos Vinicius Zonta Salermo',
'Maria Da Conceicao Do Monte Soares',
'Maria De Fatima Possel Pereira',
'Maria De Lourdes E S Mardegan',
'Maria Eunice Bernardo da Silva Jaques',
'Maria Ines De Oliveira',
'Maria Rosineia Da Conceiçao',
'Maria Teixeira Oliveira',
'Maria Teresa Scalzilli Meneghetti Eggers',
'Maria Tereza Fagundes Daniel',
'Mariana Roehrig',
'Mariele Luisa Dreher Stein',
'Marilene Araujo Bortholo',
'Mario Alves Pereira',
'Mark Robert Ross Neal',
'Marlene Marques Amaro Carlos',
'Marli Terezinha Beltramin',
'Marlon Cardan',
'Marlon De Souza Fogaca',
'Marly Verardi Bernardo',
'Mauricio Brandao Feijo',
'Maurilio Coelho',
'Mauro Jandt Nornberg',
'Mauro Luis Trucolo',
'Mauro Reis',
'Maycon David Barros Padua',
'Maysi De Fatima Cleve Kuster',
'Michael Gonçalves De Oliveira',
'Michel Alexandre Coelho',
'Michele De Oliveira Bernardino',
'Michele Sartori De Quadros',
'Miguel Lewandowski',
'Milca Jared Ribeiro Da Silva',
'Milton Cesar Lang',
'Milton Da Silva Martins',
'Milton Figueiredo Netto',
'Misael Correa',
'Moacir Auzani',
'Moacir Moreira Brum',
'Monica Bonatto Farias dos Santos',
'Monica Theml Fialho De Carvalho',
'Moraima Marenco Pinto Sobrinha',
'Morgana Zila dos Reis Camargo',
'Nadir Mendes Turchetto',
'Nagella Maria Prante Ferri',
'Nasser Marcelo Kadan',
'Natali Guedes Lara',
'Nathana Richelli Da Costa',
'Neida Marisa Ferreira Dos Santos',
'Neiva Goretti Da Silva Vale Monteiro',
'Ney Castilho Da Silva',
'Nilo Rodrigues Dos Santos',
'Nilse Conink',
'Ola Braathen',
'Orivaldo Alves De Oliveira',
'Osmar Carvalho Lemos',
'Otavio Luiz Da Silva De Vargas',
'Pamela Da Silva Cidral',
'Paolo Banti',
'Patricia Almeida Padilha',
'Patricia Fernanda Toldo Barbosa',
'Patricia Maliszewski',
'Mario Sergio Taques',
'Paulo Cardoso De Oliveira',
'Paulo Flavio Maciente',
'Paulo Fulginiti Merola',
'Paulo Henrique Carvalho Barros',
'Paulo Henrique Vieira',
'Paulo Leoni Colaco',
'Paulo Levistone Silva De Lima',
'Paulo Renato Coelho',
'Paulo Roberto da Silva Oliveira',
'Paulo Sergio Machado Duarte',
'Paulo Tetsuo Uchimura',
'Pedro Altmayer',
'Pedro Wagner Purger De Abreu',
'Peron Sales Da Costa',
'Persio Sposito',
'Rafael Artico',
'Rafael Benedito Seabra De Andrade',
'Rafael Cancelier Beloli',
'Rafael Cunha De Araujo',
'Rafael Garcia',
'Rafael Jorge Carraro De Carvalho',
'Rafaela Oliveira Soares',
'Raphael De Souza Braga',
'Raquel Alves Prestes',
'Raquel Patzdorf Da Silveira',
'Rebeca Scatrut Bronfman',
'Rejane Maria Flach',
'#N/D',
'Renata Siebert De Moraes Lawson',
'Renato Bini Anade',
'Renato Massia Louzada',
'Renato Mendonca Suello Da Silva',
'Renato Rech',
'Renato Zamora Flores',
'Rene Paul Silvero',
'Ricardo Blanke Piva',
'Ricardo Everling',
'Ricardo Luis Segatti',
'Ricardo Mitsuo Ottani',
'Rodolfo Carlos Eggers Neto',
'Rodrigo Augusto Saviski',
'Rodrigo Lemos De Lima',
'Rodrigo Luciano Burgatt De Mello',
'Rodrigo Pimentel Mendonca',
'Rodrigo Reis Marques',
'Rogerio De Freitas Ribeiro',
'Romario Manoel Simao',
'Rosane Procaska Pereira',
'Rosangela Picaluga Jasnievez',
'Rosildo Francisco Da Silva',
'Rosinete Alvina Nasario',
'Rubens Fonseca Da Luz',
'Rubia Mara da Rosa Castros',
'Sabrina De Paula Leao Bagesteiro',
'Sabrina Machado',
'Sadi Rogerio Maciel',
'Samuel Messa Soares',
'Sandro Carlos Ader Rontschky',
'Sandro Da Silva Garcia',
'Sergio De Bem Silva',
'Sibele Busch',
'Silvia Scolari Rodrigues',
'Silvio Nascimento Da Cruz',
'Simone De Fatima Iavorski',
'Simone Pereira Schneider',
'Sirlei De Fatima Araujo Rossi',
'Solange Cristina Andreassa',
'Sonia Maria Da Silva Dos Santos',
'Sonia Maria Sousa Freitas',
'Sonia Regina Leme Ferreira De Castro',
'Stefanie Pillar Muradas',
'Stefano Calis',
'Susan Hulsmeyer',
'Suzana Lucia Linhares',
'Teresinha Tavares Rossi',
'Terezinha Dos Santos Correa',
'Thais Camila Vieira Compadre',
'Thais Fernanda Ramseier',
'Thiago Dalla Santo Chepanski',
'Thiago De Jesus',
'Thiago Mamprin',
'Tiago Dival Peretto',
'Tiago Mattes Da Silva',
'Tulio Oliveira Camargo Dos Santos',
'Urbana Dos Santos Ermel',
'Valdir Alves Da Silva Filho',
'Vandre Aparecido Marengoni',
'Vania De Lourdes Marcelino Da Silva',
'Victoredson Raphael Ridao',
'Victoria Lima Da Costa',
'Vinicius Antonio Gomes',
'Vinicius Saffi Teixeira',
'Vinicius Talheimer Da Costa',
'Volnei Moraes Casturino',
'Valter Antonio Dos Santos',
'Walter Tohoru Sugaya Junior',
'Wanderley Rosa Guimaraes Jr',
'Wanessa Cavalcante Nascimento',
'William Marques',
'Zanel Rogerio Da Silva Escobar'
]

#Mensagem - Mensagem que sera enviada
mensagem = 'Tem boa notícia chegando no seu WhatsApp. Estamos iniciando a semana da regularização de dívidas! E aí, que tal ver o que podemos fazer por você? Confira as condições especiais de pagamento. '
mensagem2 = 'Responda essa mensagem e vamos conversar! Luana Muller - *Rama Advogados Associados*, representante do Canal Judicial do Banco Santander - *4007.2279*'


def buscar_contato(contato):
    campo_pesquisa = driver.find_element_by_xpath('//div[contains(@class,"copyable-text selectable-text")]')
    time.sleep(2)
    campo_pesquisa.click()
    campo_pesquisa.send_keys(contato)
    campo_pesquisa.send_keys(Keys.ENTER)
    time.sleep(1)
    campo_pesquisa.clear()
   
#Funcao que envia a mensagem
def enviar_mensagem(mensagem,mensagem2):
    campo_mensagem = driver.find_elements_by_xpath('//div[contains(@class,"copyable-text selectable-text")]')
    campo_mensagem[1].click()
    time.sleep(2)
    campo_mensagem[1].send_keys(str(mensagem) + str(mensagem2))
    campo_mensagem[1].send_keys(Keys.ENTER)


#Percorre todos os contatos/Grupos e envia as mensagens
for contato in contatos:
    buscar_contato(contato)
    enviar_mensagem(mensagem,mensagem2) 
    time.sleep(2)